/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as ReferralVoorwaardenRouteImport } from './routes/referral-voorwaarden'
import { Route as PrivacybeleidRouteImport } from './routes/privacybeleid'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OfferteRouteImport } from './routes/offerte'
import { Route as MogelijkhedenRouteImport } from './routes/mogelijkheden'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as IndexRouteImport } from './routes/index'

const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralVoorwaardenRoute = ReferralVoorwaardenRouteImport.update({
  id: '/referral-voorwaarden',
  path: '/referral-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacybeleidRoute = PrivacybeleidRouteImport.update({
  id: '/privacybeleid',
  path: '/privacybeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)
const MogelijkhedenRoute = MogelijkhedenRouteImport.update({
  id: '/mogelijkheden',
  path: '/mogelijkheden',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/contact': typeof ContactRoute
  '/mogelijkheden': typeof MogelijkhedenRoute
  '/offerte': typeof OfferteRoute
  '/portfolio': typeof PortfolioRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/referral-voorwaarden': typeof ReferralVoorwaardenRoute
  '/seo': typeof SeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/contact': typeof ContactRoute
  '/mogelijkheden': typeof MogelijkhedenRoute
  '/offerte': typeof OfferteRoute
  '/portfolio': typeof PortfolioRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/referral-voorwaarden': typeof ReferralVoorwaardenRoute
  '/seo': typeof SeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/contact': typeof ContactRoute
  '/mogelijkheden': typeof MogelijkhedenRoute
  '/offerte': typeof OfferteRoute
  '/portfolio': typeof PortfolioRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/referral-voorwaarden': typeof ReferralVoorwaardenRoute
  '/seo': typeof SeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algemene-voorwaarden'
    | '/contact'
    | '/mogelijkheden'
    | '/offerte'
    | '/portfolio'
    | '/privacybeleid'
    | '/referral-voorwaarden'
    | '/seo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemene-voorwaarden'
    | '/contact'
    | '/mogelijkheden'
    | '/offerte'
    | '/portfolio'
    | '/privacybeleid'
    | '/referral-voorwaarden'
    | '/seo'
  id:
    | '__root__'
    | '/'
    | '/algemene-voorwaarden'
    | '/contact'
    | '/mogelijkheden'
    | '/offerte'
    | '/portfolio'
    | '/privacybeleid'
    | '/referral-voorwaarden'
    | '/seo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  ContactRoute: typeof ContactRoute
  MogelijkhedenRoute: typeof MogelijkhedenRoute
  OfferteRoute: typeof OfferteRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacybeleidRoute: typeof PrivacybeleidRoute
  ReferralVoorwaardenRoute: typeof ReferralVoorwaardenRoute
  SeoRoute: typeof SeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral-voorwaarden': {
      id: '/referral-voorwaarden'
      path: '/referral-voorwaarden'
      fullPath: '/referral-voorwaarden'
      preLoaderRoute: typeof ReferralVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacybeleid': {
      id: '/privacybeleid'
      path: '/privacybeleid'
      fullPath: '/privacybeleid'
      preLoaderRoute: typeof PrivacybeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mogelijkheden': {
      id: '/mogelijkheden'
      path: '/mogelijkheden'
      fullPath: '/mogelijkheden'
      preLoaderRoute: typeof MogelijkhedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  ContactRoute: ContactRoute,
  MogelijkhedenRoute: MogelijkhedenRoute,
  OfferteRoute: OfferteRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacybeleidRoute: PrivacybeleidRoute,
  ReferralVoorwaardenRoute: ReferralVoorwaardenRoute,
  SeoRoute: SeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
